# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '24.3.0'
    displayName: 'Install Node.js 24.3.0'
 
  - script: |
      node -v
      npm -v
    displayName: 'Show Node.js and npm versions'
  
  - script: npm ci --install-strategy hoisted
    displayName: 'Install dependencies'

  - script: |      
      npx playwright install --with-deps
    displayName: 'Install Playwright'
    
  - script : |
      npx playwright test --output=test-results
    displayName: 'Run Playwright tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '.last-run.json'
      testResultsFormat: 'json'
      failTaskOnFailedTests: true
    displayName: 'Publish Playwright Test Results'

  - publish: test-results
    artifact: test-results
    displayName: 'Publish Test Results Artifact'
